name: price_scraper
description: Price scrapper API.
version: 0.0.1
author: Asyraf

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: ^3.0.0
  http: "^0.12.0"

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0
